In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
x = np.array(range(400)).reshape(100,4)
y = np.array(range(100)).reshape(100,1).ravel()

In [2]:
estimator_withParams = RandomForestRegressor(n_estimators=300, max_features="auto",
                           min_samples_split=4,
                           min_samples_leaf=4, oob_score=False, n_jobs=-1)
estimator_withParams.fit(x,y)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=4,
           min_samples_split=4, min_weight_fraction_leaf=0.0,
           n_estimators=300, n_jobs=-1, oob_score=False, random_state=None,
           verbose=0, warm_start=False)

In [56]:
X_test = np.array(range(10000*4)).reshape(-1,4)

In [57]:
import time
start_time = time.time()
estimator_withParams.predict(X_test)
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.861119031906 seconds ---


In [58]:
import time
start_time = time.time()
for i in X_test:
    #print i
    estimator_withParams.predict([i])
print("--- %s seconds ---" % (time.time() - start_time))

KeyboardInterrupt: 

In [24]:
days = pd.date_range("2015-09-09",periods=100)
shop1 = np.array(range(0,100))
shop2 = np.array(range(100,200))
df = pd.DataFrame({'day':days,1:shop1,2:shop2})

In [43]:
df

1    2        day
0    0  100 2015-09-09
1    1  101 2015-09-10
2    2  102 2015-09-11
3    3  103 2015-09-12
4    4  104 2015-09-13
5    5  105 2015-09-14
6    6  106 2015-09-15
7    7  107 2015-09-16
8    8  108 2015-09-17
9    9  109 2015-09-18
10  10  110 2015-09-19
11  11  111 2015-09-20
12  12  112 2015-09-21
13  13  113 2015-09-22
14  14  114 2015-09-23
15  15  115 2015-09-24
16  16  116 2015-09-25
17  17  117 2015-09-26
18  18  118 2015-09-27
19  19  119 2015-09-28
20  20  120 2015-09-29
21  21  121 2015-09-30
22  22  122 2015-10-01
23  23  123 2015-10-02
24  24  124 2015-10-03
25  25  125 2015-10-04
26  26  126 2015-10-05
27  27  127 2015-10-06
28  28  128 2015-10-07
29  29  129 2015-10-08
..  ..  ...        ...
70  70  170 2015-11-18
71  71  171 2015-11-19
72  72  172 2015-11-20
73  73  173 2015-11-21
74  74  174 2015-11-22
75  75  175 2015-11-23
76  76  176 2015-11-24
77  77  177 2015-11-25
78  78  178 2015-11-26
79  79  179 2015-11-27
80  80  180 2015-11-28
81  81  181 2015-11-29
82  82  182 2015-11-30
83  83  183 2015-12-01
84  84  184 2015-12-02
85  85  185 2015-12-03
86  86  186 2015-12-04
87  87  187 2015-12-05
88  88  188 2015-12-06
89  89  189 2015-12-07
90  90  190 2015-12-08
91  91  191 2015-12-09
92  92  192 2015-12-10
93  93  193 2015-12-11
94  94  194 2015-12-12
95  95  195 2015-12-13
96  96  196 2015-12-14
97  97  197 2015-12-15
98  98  198 2015-12-16
99  99  199 2015-12-17

[100 rows x 3 columns]

1        day
0    0 2015-09-09
1    1 2015-09-10
2    2 2015-09-11
3    3 2015-09-12
4    4 2015-09-13
5    5 2015-09-14
6    6 2015-09-15
7    7 2015-09-16
8    8 2015-09-17
9    9 2015-09-18
10  10 2015-09-19
11  11 2015-09-20
12  12 2015-09-21
13  13 2015-09-22
14  14 2015-09-23
15  15 2015-09-24
16  16 2015-09-25
17  17 2015-09-26
18  18 2015-09-27
19  19 2015-09-28
20  20 2015-09-29
21  21 2015-09-30
22  22 2015-10-01
23  23 2015-10-02
24  24 2015-10-03
25  25 2015-10-04
26  26 2015-10-05
27  27 2015-10-06
28  28 2015-10-07
29  29 2015-10-08
..  ..        ...
70  70 2015-11-18
71  71 2015-11-19
72  72 2015-11-20
73  73 2015-11-21
74  74 2015-11-22
75  75 2015-11-23
76  76 2015-11-24
77  77 2015-11-25
78  78 2015-11-26
79  79 2015-11-27
80  80 2015-11-28
81  81 2015-11-29
82  82 2015-11-30
83  83 2015-12-01
84  84 2015-12-02
85  85 2015-12-03
86  86 2015-12-04
87  87 2015-12-05
88  88 2015-12-06
89  89 2015-12-07
90  90 2015-12-08
91  91 2015-12-09
92  92 2015-12-10
93  93 2015-12-11
94  94 2015-12-12
95  95 2015-12-13
96  96 2015-12-14
97  97 2015-12-15
98  98 2015-12-16
99  99 2015-12-17

[100 rows x 2 columns]

In [59]:
t1 = np.array(range(16)).reshape(4,4)
t2 = t1+4

In [62]:
t3 = np.hstack([t1,t2])


In [64]:
t3[:,:4]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [67]:
p1=[t1]*4
p1

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]), array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]), array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]), array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [68]:
t4 = np.hstack(p1)

In [77]:
from datetime import datetime
a = datetime.now()


In [81]:
a = {1:2,2:3}


In [82]:
a.pop(2)

3

In [84]:
a=[12,3,4]

In [86]:
a[-20:]

[12, 3, 4]

In [88]:
c=np.round(a).astype(int)

In [90]:
c.reshape(-1,1)

array([[12],
       [ 3],
       [ 4]])

In [99]:
t4

array([[ 0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11,  8,  9, 10, 11,  8,  9, 10, 11],
       [12, 13, 14, 15, 12, 13, 14, 15, 12, 13, 14, 15, 12, 13, 14, 15]])

In [98]:
np.hstack([t4,t4[:,:0]])

array([[ 0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11,  8,  9, 10, 11,  8,  9, 10, 11],
       [12, 13, 14, 15, 12, 13, 14, 15, 12, 13, 14, 15, 12, 13, 14, 15]])

In [100]:
tmp = pd.DataFrame(np.array(range(16)).reshape(4,4),columns=['a','b','c','d'])
b = set(tmp['a'])

In [104]:
t4[[False,True,True,False],3:6]

array([[ 0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11,  8,  9, 10, 11,  8,  9, 10, 11],
       [12, 13, 14, 15, 12, 13, 14, 15, 12, 13, 14, 15, 12, 13, 14, 15]])

In [118]:
tmp[tmp['a']==0].iloc[:,np.logical_and(tmp.columns!='a',tmp.columns!='c')]

b   d
0  1   3
2  9  11

In [116]:
tmp.iloc[2,0]=0

In [117]:
tmp

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   0   9  10  11
3  12  13  14  15

In [123]:
t4[[True,False,True,True],:]

/home/hao/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: in the future, boolean array-likes will be handled as a boolean array index
  if __name__ == '__main__':


array([[4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7],
       [0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3],
       [4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7],
       [4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7]])

In [124]:
t4

array([[ 0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11,  8,  9, 10, 11,  8,  9, 10, 11],
       [12, 13, 14, 15, 12, 13, 14, 15, 12, 13, 14, 15, 12, 13, 14, 15]])

In [129]:
y = np.arange(35).reshape(5,7)
print y

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [132]:
t4[np.array(tmp['a']==0),:]

array([[ 0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3],
       [ 8,  9, 10, 11,  8,  9, 10, 11,  8,  9, 10, 11,  8,  9, 10, 11]])